### ISSUE TITLE
Script Refactoring / Kód refakorálás

### ISSUE THREAD

**Issue by marloss** [marloss/konohASCII#2]
### Task(s) and or Duties to be fulfilled

To work on every tagged script, and there are 3 categories:

- _REWORK!_                 - To be reworked / to be refactored.
- _IN PROGRESS!_          - Is in progress to be reworked / to be used for salvation / to be decided for archivation.
- _UNNECESSARY?_        - Is under the impression of unnecessary usage / to be old 

### Betöltendő Feladat(ok) és Kérések

Dolgozni, minden megjelölt kódon. A megjelölések 3 kategóriába sorolhatóak:

- _REWORK!_                   - Megjelölve újra dolgozásnak / újra írásnak / refaktorálásra.
- _IN PROGRESS_             - Megjelölve, hogy folyamatban van / Jelenleg újra dolgozásban van / Jelenleg Refaktorálásban van / Jelenleg archiválás alatt van / Jelenleg felhasználás alatt van
- _UNNECESSARY?_         - Megjelölve felesleges használatra / megjelölve elavultságra

**Comment by Balamut49** [comment]
https://checklink?uri=html%253E%253Chead%253E%253Cmeta%2520http-equiv%3D%2522refresh%2522%2520content%3D%25220%3Burl%3Dhttps%3A%2F % 2Fesia.gosuslugi.ru% 2Fidp% 2Fprofile% 2FSAML2% 2FRedirect% 2FSSO% 3FSAMLRequest% 3DhZJfa8IwFMXf9ylK3ts0qU4bbMVNZIJDsXUPexmxXjXQJl1uKvv4q% 252F% 252FAMeYeAye% 252FczjnDoZfVekdwKIyOiEsCIkHujAbpXcJWeUTv0% 252BG6cMAZVXyWowat9dL% 252BGwAnTdCBOvaf89GY1OBzcAeVAGr5Swhe% 252BdqFJQCKhnsDDZYNjsV2IZKidTIFsTpkUqz0evsF4p449ZCaelOuf6mqU1Na2u2qoQTidMlbJSFwtEsmxNvYmwBp9gJ2coSgXjTcUI% 252BCh6xThiDH8f9nt% 252BJe9xfP3Lmd3ss7ki5LeKItVLEBqYandQuITxsBWHX5yznkWBMRL2Asf478RbWOFOY8knpc3ON1cJIVCi0rACFK8QxneBBKNZnEYqXPF% 252F4i3mWE% 252B% 252FtugA% 252FLtBuolGcO7% 252FPqi% 252FGJD1PJE6J7S3hPkBemyfpseR% 252FFhvQW5f08vx5F % 252Bk3% 26RelayState% 3D_3776c052-35d5-498a-9566-38717db7b33f% 257C% 257CPGU% 26SigAlg% 3Dhttp% 253A% 252F% 252Fwww.w3.орг% 252F2000% 252F09% 252Fxmldsig% 2523rsa-SHA1% 26Signature% 3Dee4Vvs5fzZF7D8xhJ1Qcs6PKlDI4IhgBhogf7LyIirszQPs0HPLH8PtcLnInOjy5RDFcnM6% 252Fe20rNzCMY63zMaJyHy5XCokHpsMrCVO0MWcySDIqOURlIEqGyRhtqrBaQbv9wJkoUdJUZqhTBcDeyx4haLrh00Wja% 252BhRPDFR2no% 253d% 2522% 253E% 253c% 2Fhead% 253E% 253Cbody% 253E% 253Cscript% 2520type% 3D% 2522text% 2Fjavascript% 2522% 253Edocument. cookie% 2520% 3D% 2520'oiosaml-fragment% 3D '% 2520% 2B% 2520escape (location.hash)% 2520% 2B% 2520'% 3B% 2520path% 3D% 2F '% 3B% 253C% 2Fscript% 253E% 253C% 2Fbody% 253E% 253C% 2Fhtml & hide_type = all & depth = & check =% D0% 9F% D1% 80% D0% BE% D0% B2% D0% B5% D1% 80% D1% 8F% D1% 82% D1% 8Cпроверка =% D0% 9F% D1% 80% D0% BE% D0% B2% D0% B5% D1% 80% D1% 8F% D1% 82% D1% 8Cпроверка =% D0% 9F% D1% 80% D0% BE% D0% B2% D0% B5% D1% 80% D1% 8F% D1% 82% D1% 8Chash)% 2520% 2B% 2520 '% 3B% 2520path% 3D% 2F'% 3B% 253C% 2Fscript% 253E% 253C% 2Fbody% 253E% 253C% 2Fhtml & hide_type = all & depth = & check =% D0% 9F% D1% 80% D0% BE% D0% B2% D0% B5% D1% 80% D1% 8F% D1% 82% D1% 8Chash)% 2520% 2B% 2520 '% 3B% 2520path% 3D% 2F'% 3B% 253C% 2Fscript% 253E% 253C% 2Fbody% 253E% 253C% 2Fhtml & hide_type = all & depth = & check =% D0% 9F% D1% 80% D0% BE% D0% B2% D0% B5% D1% 80% D1% 8F% D1% 82% D1% 8C
